# Customization for vim shell



##########
# Customization commands
##########

syntax on
set number
set autoindent
set ruler
color elflord
autocmd FileType make set noexpandtab shiftwidth=8 softtabstop=0
