# Customization for vim shell

# Shebang for Bash
#!/bin/bash


##########
# Customization commands
##########

syntax on
set number
set autoindent
set ruler
color darkblue
autocmd FileType make set noexpandtab shiftwidth=8 softtabstop=0
